[package]
name = "ws-server-example"
edition = "2024"
publish = false

[dependencies]
musli-web = { path = "../..", features = ["axum08"] }
api = { package = "ws-api-example", path = "../api" }

anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["ws"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
